### ISSUE TITLE
Issues with running HelloActivty sample

### ISSUE THREAD

**Issue by darewreck54** [temporalio/samples-java#32]
I'm trying to run the HelloWorld example and getting the following error.  Wonder is there something i'm missing in the setup.

Steps I did:
- git clone https://github.com/temporalio/temporal-java-samples
- cd temporal-java-samples
- ./gradlew build
-  curl -L https://github.com/temporalio/temporal/releases/latest/download/docker.tar.gz | tar -xz --strip-components 1 docker/docker-compose.yml
 docker-compose up
- validated the temporal site is up on localhost:8088
- ./gradlew -q execute -PmainClass=io.temporal.samples.hello.HelloActivity.  I think get the following error below.

```
20:45:17.827 [Workflow Executor taskQueue="HelloActivity", namespace="default": 1] WARN  i.t.internal.common.GrpcRetryer - Retrying after failure
io.grpc.StatusRuntimeException: INTERNAL: grpc: error unmarshalling request: proto: wrong wireType = 0 for field ScheduleToCloseTimeout
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
        at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondWorkflowTaskCompleted(WorkflowServiceGrpc.java:2653)
        at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.lambda$sendReply$0(WorkflowWorker.java:353)
        at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109)
        at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127)
        at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106)
        at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.sendReply(WorkflowWorker.java:346)
        at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:304)
        at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:273)
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by darewreck54** [comment]
This is probably not a problem, but just not compatible with 0.28 temporal server.
