### ISSUE TITLE
HelloCron - Unsupported field

### ISSUE THREAD

**Issue by anborg** [temporalio/samples-java#49]
I changed hellocron to print timestamp along with message

>Caused by: io.temporal.failure.ApplicationFailure: message='Unsupported field: Year', >type='java.time.temporal.UnsupportedTemporalTypeException', nonRetryable=false

I see two issues 
1. Date format is causing error : Caused by: io.temporal.failure.ApplicationFailure: message='Unsupported field: Year', 
2. While the nature of error is fatal (no use retrying) I still see the wf executing<==========---> 80% EXECUTING [6m 35s]

Questions: 

1. Why printing the below date time stamp did not work? If I choose to keep the date format code as-is, should I change any temporal-config to make the workflow execute without error? 
2. Is "retry" an expected behavoir for an obvious non-retryable scenario like 

```
  static class GreetingActivitiesImpl implements GreetingActivities {
    static final DateTimeFormatter MYDATE_FORMATTER = DateTimeFormatter.ISO_LOCAL_DATE_TIME;

    @Override
    public void greet(String greeting) {
      System.out.println(
          MYDATE_FORMATTER.format(Instant.now().truncatedTo(ChronoUnit.SECONDS))
              + "From "
              + Activity.getExecutionContext().getInfo().getWorkflowId()
              + ": "
              + greeting);
    }
  }
```

error: 
```log
14:34:07.311 [workflow-method] ERROR i.t.i.s.POJOWorkflowImplementationFactory - Workflow execution failure WorkflowId=HelloCron, RunId=f600d571-be09-4b4
6-a043-f8e1a5f28c78, WorkflowType=GreetingWorkflow
io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Greet', activityId='2d407c54-4418-3158-a003-1de6c17cf62a', ident
ity='21484@TOHQLP922', retryState=RETRY_STATE_TIMEOUT
        at java.base/java.lang.Thread.getStackTrace(Thread.java:1606)
        at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48)
        at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:59)
        at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:65)
        at com.sun.proxy.$Proxy7.greet(Unknown Source)
        at io.temporal.samples.hello.HelloCron$GreetingWorkflowImpl.greet(HelloCron.java:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflo
wImplementationFactory.java:289)
        at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:253)
        at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:52)
        at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:119)
        at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:104)
        at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.temporal.failure.ApplicationFailure: message='Unsupported field: Year', type='java.time.temporal.UnsupportedTemporalTypeException', nonRetryable=false
        at java.base/java.time.Instant.getLong(Instant.java:602)
        at java.base/java.time.format.DateTimePrintContext$1.getLong(DateTimePrintContext.java:205)
        at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
        at java.base/java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2696)
        at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2335)
        at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2335)
        at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1843)
        at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817)
        at io.temporal.samples.hello.HelloCron$GreetingActivitiesImpl.greet(HelloCron.java:85)
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source:0)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:279)
        at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:218)
        at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:183)
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:194)
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154)
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
<==========---> 80% EXECUTING [6m 35s]
> :execute


```

**Comment by tsurdilo** [comment]
@anborg looking into this next. will report back asap

**Comment by tsurdilo** [comment]
@anborg 
1. You get the error because you need to specify a timezone in order to format an Instant. So you can do:

           static final DateTimeFormatter MYDATE_FORMATTER =
          DateTimeFormatter.ISO_LOCAL_DATE_TIME.withZone(ZoneId.of("UTC"));

and it should not throw that error. The error is not specific to Temporal. 

2. Yes, Activities in Temporal are retried by default. If you do not want to retry on specific error, add it to "setDoNotRetry" in Activity retry options.

Hope this helps. I will close this issue, feel free to reopen if there are any more questions about it.

**Comment by anborg** [comment]
Thanks for the info. I'll try to recall where my example code is! I forgot that I tried this tool, and typed this question.
